SMI_CONFIG_PATHS = "SMI_CONFIG_PATHS"
SMI_PROFILES = "SMI_PROFILES"
OPTIONAL_CONFIG_FILE = "SMI_OPTIONAL_CONFIG_FILE"

APPLICATION_FILE_PREFIX = "application"
APPLICATION_FILE_PREFIXES = [APPLICATION_FILE_PREFIX]
APPLICATION_FILE_SUFFIXES = ["json", "yml", "yaml"]  # In overloading order
