SMI_CONFIG_PATHS = "SMI_CONFIG_PATHS"
SMI_PROFILES = "SMI_PROFILES"
SMI_OPTIONAL_CONFIG_FILES = "SMI_OPTIONAL_CONFIG_FILES"
SMI_NAME = "SMI_NAME"

APPLICATION_FILE_PREFIX = "application"
APPLICATION_FILE_PREFIXES = [APPLICATION_FILE_PREFIX]
APPLICATION_FILE_SUFFIXES = ["json", "yml", "yaml"]  # In overloading order
